font size reduce
ofast-team/frontend pull request #81
Opened 2024-02-27 01:44 UTC by sd0623

Just setting PR now, will decide in tomorrow's meeting so can actually decide the font size better than screenshot.

2024-02-27 18:35 UTC, sd0623 commented
<img width="1440" alt="Screenshot 2024-02-27 at 1 34 09 PM" src="https://github.com/ofast-team/frontend/assets/84353905/ad77af12-6b77-4e2c-9133-f9bd4f48e894">
<img width="1440" alt="Screenshot 2024-02-27 at 1 34 05 PM" src="https://github.com/ofast-team/frontend/assets/84353905/cf576620-c1d7-4f36-b337-48a2241f00a5">

2024-02-27 18:36 UTC, sd0623 commented
<img width="1440" alt="Screenshot 2024-02-27 at 1 34 41 PM" src="https://github.com/ofast-team/frontend/assets/84353905/8a589fbd-11c6-4ccd-955e-f8b9602372bf">
<img width="1440" alt="Screenshot 2024-02-27 at 1 34 37 PM" src="https://github.com/ofast-team/frontend/assets/84353905/33a403db-d720-4459-8a42-87e50025024d">

2024-03-05 22:06 UTC, AsirAAlam requested changes
I opened up the branch and hosted it locally. It's nice that we can fit more content on the pages now. My only concern was that the body text looked too small. So I tried reverting your changes in `App.tsx` (left comments to indicate those lines) and I thought it looked better (including the h3). 

This can be a subjective matter so another set of eyes might help. But I personally think reverting the changes in `App.tsx` would be better for reading comfort. And even after reverting that, the table of contents seemed small. So, I think it would be nice to make the font for the TOC the same as the lesson body text (or maybe ever so slightly smaller).

2024-03-05 23:23 UTC, AsirAAlam approved these changes

2024-03-06 05:32 UTC, merged